services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - mongodb_data:/data/db

  backend:
    image: jordi9675/teachme-backend:latest
    container_name: teachme-backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/BBDD
    depends_on:
      - mongodb
    mem_limit: 256m
    mem_reservation: 128m

  frontend:
    image: jordi9675/teachme-frontend-v2:latest
    container_name: teachme-frontend-v2
    ports:
      - "51139:51139"
    depends_on:
      - backend
    mem_limit: 512m
    mem_reservation: 256m

volumes:
  mongodb_data:
    driver: local
